services:
  - type: web
    name: summarizer-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: MODEL_NAME
        value: sshleifer/distilbart-cnn-12-6
