services:
  - type: web
    name: summarization-api
    env: python
    plan: free
    buildCommand: |
      rm -rf /opt/render/project/.cargo
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: >
      gunicorn app:app
      --bind 0.0.0.0:$PORT
      --workers=${GUNICORN_WORKERS:-2}
      --threads=${GUNICORN_THREADS:-2}
      --timeout=${GUNICORN_TIMEOUT:-120}
      --worker-class=gevent
    envVars:
      - key: CARGO_HOME
        value: /opt/render/project/.cargo

      # 最大トークン長（Flask側で読み取り、入力カットに使う）
      - key: MAX_TOKENS
        value: "512"

      # Gunicorn調整値（Renderのダッシュボードからも変更可能）
      - key: GUNICORN_TIMEOUT
        value: "120"
      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_THREADS
        value: "2"
