services:
  - type: web
    name: summarization-api
    env: python
    plan: free
    autoDeploy: true
    # 任意でリージョン指定
    # region: oregon

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt

    startCommand: >
      gunicorn app:app
      --bind 0.0.0.0:$PORT
      --workers=$GUNICORN_WORKERS
      --threads=$GUNICORN_THREADS
      --timeout=$GUNICORN_TIMEOUT
      --worker-class=gevent

    healthCheckPath: /health

    envVars:
      - key: API_KEY
        sync: false  # Render ダッシュボードから設定

      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_THREADS
        value: "2"
      - key: GUNICORN_TIMEOUT
        value: "120"

      - key: OMP_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
