services:
  - type: web
    name: summarizer-api
    env: python
    plan: starter
    buildCommand: ./install.sh
    startCommand: gunicorn app:app --workers=1 --threads=8 --timeout=0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
