services:
  - type: web
    name: summarizer-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --timeout=120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
